version: '3'

services: 

  crawler:
    build: .
    command: python3 /usr/app/crawler.py
    volumes:
      - "./scripts:/usr/app:ro"
      - "./database:/usr/database:rw"
    environment:
      START_LINK: "https://www.lemonde.fr"
      LEMONDE_EMAIL: ${LEMONDE_EMAIL}
      LEMONDE_PASSWORD: ${LEMONDE_PASSWORD}
      RETRIEVE_RELATED_ARTICLE_LINKS: "false"
      RETRIEVE_EACH_ARTICLE_LINKS: "false"
      IS_DOCKER: "true"
